version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

jobs:
  section_07_test_app:
    <<: *defaults
    working_directory: ~/project/03_CircleCI/sports-classifier-api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox

  section_07_deploy_app_to_heroku:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Deploy to Heroku
          command: |
            git subtree push --prefix 03_CircleCI/sports-classifier-api https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  section_07_test_and_upload_regression_model:
    <<: *defaults
    working_directory: ~/project/03_CircleCI/model-package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Test the model
          command: |
            tox
      - run:
          name: Publish model to Gemfury
          command: |
            tox -e publish_model


  section_08_deploy_app_container_in_heroku:
    <<: *defaults
    steps:
      - setup_remote_docker:
          # Supported versions: https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 20.10.6
      - checkout:
          path: ~/project
      - run:
          name: Build image
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            make build-ml-api-heroku
      - run:
          name: Push Image to Heroku
          command: |
            # Push the built container to the Heroku image registry
            make push-ml-api-heroku
      - run:
          name: Release to Heroku
          command: |
            make release-heroku


tags_only: &tags_only
  filters:
    branches:
      only:
        - master
        - development
        - dev_aiden
    tags:
      only: /^.*/

workflows:
  version: 2
  section_07:
    jobs:
      - section_07_test_app
      - section_07_deploy_app_to_heroku:
          requires:
            - section_07_test_app
          filters:
            branches:
              only:
                - master
                - dev_aiden
                - development
      # upload after git tags are created
      - section_07_test_and_upload_regression_model:
          <<: *tags_only
      - section_08_deploy_app_container_in_heroku:
          filters:
            branches:
              only:
                - master
                - dev_aiden
                - development

